# secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: environment
  namespace: donetick
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: Merge
stringData:
  DT_JWT_SECRET: changeme
  DT_OAUTH2_CLIENT_ID: changeme
  DT_OAUTH2_CLIENT_SECRET: changeme