# Disabled because it would be overwritten on every deployment.
# Cannot use the clustertool managed secrets, because renovate bot auto-updated to a talos version that is not supported by clustertool.
# Have to wait until clustertool supports this version.
# Just Truecharts things *sigh*

## secret.yml
#apiVersion: v1
#kind: Secret
#metadata:
#  name: environment
#  namespace: donetick
#stringData:
#  DT_JWT_SECRET: changeme
#  DT_OAUTH2_CLIENT_ID: changeme
#  DT_OAUTH2_CLIENT_SECRET: changeme