apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aria/ks.yaml
  - audiobookshelf/ks.yaml
  - bahuma-abrechnung/ks.yaml
  - ddns-updater/ks.yaml
  - donetick/ks.yaml
  - jellyfin/ks.yaml
  - homepage/ks.yaml
  - immich/ks.yaml
  - kvb-kt/ks.yaml
  - minecraft/ks.yaml
  - nextcloud/ks.yaml
  - paperless-ngx/ks.yaml
  - truenas/ks.yaml
  - vaultwarden/ks.yaml
#  - kubernetes-dashboard/ks.yaml
