apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8WaiIXE+WrTKG2lsk/f7rAV4dyoL8tStyOjC8XiRTUGz/OTvV1eX6+vwwlptfX4PAG5NWMJTlZP30Iq4z0PxXXtfPUT0H2a5CdI7rgER+HZfz4esqPAyUavruNKfxIKwhDtlctpt3q0XGZvFTCytswa9vfg+GwzSPNWRLyfqimvChInQKyjb/PTeEaENzXWOf+KTxXGHg4YEP6nbH0YIR52drJLQxG4CujVTE6+cOVOGp/JvDTF18HV3xE4AeHf7TLPneNz2gmUoVXE+O+ZtcdNdKI3rtIQguppIijGgDVddwBABY01THb4oRXvgmS7aB3Jcc/iOsasiPeKd7h8B+k7TLe64P55Lqh1OQfecbx2vwhw/LxjgAWqiPmN1HsqV,iv:C28rrm+h5c4iO4t+SKjOAGis7JKVL0aXdHR3kHOT9+U=,tag:smLF5iuluLIbnkgnb4wOIg==,type:str]
    identity.pub: ENC[AES256_GCM,data:tzjYkCbadHbpik0ZAElHPm30IgfWZ9AF6mj5EK4zC1k0Dh7X6KDQt+yPNSuKovWTM7BQJbV7Y1C6DIqytvOtizbnH/nc382ftxWsJNycK22nEYHtKDMCaXj1lhRRtdq37iuAXHxvV/DeBgg2IAwQsdPcmYOCM4UbLNDA3rEa93aiPfzHAtBwyyXglAphHx6LWwoG/UOJEYHVujt1HzElL2C0pVjg+WBmsfJ5xGXAmpVgzynAwyYT8CzKtawegMEyZ93s/5KPbyUJWpG9Ew==,iv:RNL/EokK/LrCXR7WCg/midiVY4WtSr0qRqFF+/BxP6A=,tag:9UMOUjZm41tiVugQ6k9Ijw==,type:str]
    known_hosts: ENC[AES256_GCM,data:WNkPwQ+SYrqBZt7vOUJnbsi0PsxO56PjdDiujGB6em0igXoYnIAWEhIELl6po+aUu3guVnjqZygJhhSDtMuOiOUiFteuEB62yhCt5PpVu+0BBGDlhQfneb88bDgj1sCQ48lYU7p0/Jaq4XQrQqYF8fzTmQ6KR60qP4GgmLou9I8w31eF6ukxmSfTaR3xMODSpoL62RUrOeVQFXpPsvAPjalphNGK04doLvnO,iv:9ZlCF6fJY+DOVcudt90KKLXFTwKPWUNNtuDQ8xauaZE=,tag:1Ecm7V3bJLxdwrWoM7rh4Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcHdvOUlUa0JKVzNaMGQ2
            TElKSFAxb3o2NXhFTVQ0Z2pacW9VR2g4WTBzCkU2NWlGR2xmNHZQYW1vR2wzVFFo
            Q1IvOGhaeFYrVTNwKytvek4wSTMvYWMKLS0tIHc1alVnNTU5elB5cC9LMGZkdnlG
            ZHZUaklraUVranJPa2RPNFJxZGRaNGMKXXapP3vEonpUEk+SiYadmR1D0h/A/4g5
            IBgzIGIV+RXQ2wRO4KxH6Y5G5W2PJXcza3aoU3is39Qmd8B9gQ109A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-12T16:26:19Z"
    mac: ENC[AES256_GCM,data:B79FJiEDE/bUYnsdfskQ5fOUQs+6on1WPFyKKXCInLnslPmmhYFDGnVIwCo85AJf+IU1cmwB6MGunjEDSVBw1VhkDXrJ+MKn+9/BZCzR/rdcoMLgwfjH2ucfqhKJCPTRcDSnQ3sp2kYD1eiI0BAKGF1KyrM8ImvH9GqscsFvQbM=,iv:3Qr6bOwDQGmuZpOEd/x6wiKwOJsqSURB0Z5Z/N3Gasg=,tag:PDAHamFNjRFIB/q8oaQ7jg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
