apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0RpAB6z8awk+zErhd8q2aT+q/AqNzTgaBHoh/0zPd2qPHhhKPKxAuc6IZXiNrpGQLbTlsAY1CCxNCLvIBsxHHTbjxliOo6tTb5KR/q3vsLf/i4jM7KQPwh589gn1sDpTlJ7hjxHYnVhgtzOMxcoiGh82zPCoXVCno7IpTTwJYmYtqj5JpaUZuAUhF2ZYv1R5nJQbBihWGKUWiVQxud34deHfJInfL3zqQuFc4oEtwSnI6Ysy+WLR2JzgNpniEQriOC9HS/3sTOvoQ2EqrAITGMCxjuUTWaTxyhOJft0/rJIa3U2sdnCHjHUGiZBM47odDzWIogyHUDN8v/2KB/+quNTYe629j/q/rneSQHb4wBBPQt3s64XdRJh0bkz0HqmD,iv:B8aezxVW5e7ouK11A9UnABUn4HSDLaI7Qn3i7u2Bfc4=,tag:sblfDRGP1BMLV9wJHuh0kg==,type:str]
    identity.pub: ENC[AES256_GCM,data:M6Zr97O03P3Ddq28p3kPAHMVke36VXhu9hbSnTH1XhoiGzAIfAcPW9pkmx02f7tskcKsN9knfl/JNXrL71+YYUSNcAIn3/BUKtusS0mSAqlBRTYMqJnYoRHwAdy3jUe3BoXG6NU8ZB/8BGSNhHDHZdkKmOrCPEo4W4Egokf5fnZHI4nHfH89cs41b3m3XuWPlO2bDpiBdBw/d448dSNpqf534Vaz4b7GXx+TswbGyY4LphbYgPvu0FI4U9WZ359lHyJ/R3BZf4nmmrnSdw==,iv:a77mdV9ZKgnpwQiXu938yXaaCRfOBNQuQ0eW4UYoz6M=,tag:CA4RXM4khGhAuKlu3vM+zw==,type:str]
    known_hosts: ENC[AES256_GCM,data:PIeVxzoKSLtmUAuHkG89xFpRdTy4PO04/m6l6nlo9IV0tyyv0/YD9HQS+ntoZC16OCFQGYEdGpw89EO1FaZa/zfU/9pHJKpSzDvsJI2xWQSuNMo35J0eIa1K+sEwJNXl1eWDgQqW2VkkYFA82mJar+vJwRZOnZ6ecggxtEe5Gwn/Ym5FsLjR5KNVl/QcrmxgN4RP2C2GC9TpHGUG6acsgmYxImoJwRd00ZsR,iv:OLx/bYpV8n7ix8mjPURTs9iUG+moPMInpx68jC9eU9A=,tag:sQDQWVOsqgoqR61yYKjaCg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRGxWRVZ1MThXaGZaL3BK
            UXJ5RnBFWjd4RkV4M0dVU3JlNlBnaFlqbUYwCmltYWJzYzVRUEVSbTFGOVIrZ3pT
            SnM0OU5mSmtycENSdWVDbStvZXFSS0kKLS0tIFRwQXhac2UybjRQaC9NMldFZ0ZM
            cmtDNFpSV2hqK1dmNlJPcXMwRUZqNTgKyAmB5HxVGxRZcN8czAUVqjhbOy02nGjy
            enVlyCf55zwOFCL6mJYFYxg5vHDBnp37/XKemEIKVVS1tlrgU1G2Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T10:27:25Z"
    mac: ENC[AES256_GCM,data:nYIMtsTnHdXHc+DLxo925YsbTvD3euT76RkYkVtfgHdBn8e6X9tft1O8ebvbP4r8C/DEktrjB72sdtnz2pqOEdnqwYd8N6H37se5BYone67vlo5qkj+w78RXreigNX1hveKQCu7g9lSYZ9tzJ/aNHtlWPai2TooWStO7qjXyi/I=,iv:YM2Fe7vEj6IEynGbpT6DanHhr5g/4J0HFTV6jTvgX9E=,tag:G8y25Z5xMElkCbuLxUYtZg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
