apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:OAr152WHuKXOxwhiO117kzpOzsNeByCkoZINfATksl9yJm9MFMVhLCyjfovx6JEgD0j1xrhdhiH3SUlWZF1yrAw6Hoo0WV1mh0XcFH7+vPcxDJXdvYYNaoSP+rxTfAu/SqYFRv7jpyyt3buuOBXndWS/8W+2/O5WG57CklNzHUzcyXmi+TYzF/xaTdrE06omhVO/iKoZUP2dhG5CaoaQBPrYk2uRYJN2XxY/Ff2BfsTeg71UPwvK1FU/9iKnnKP1+16uSUWe3tj6Cb3VcMVd7Cd15ZABdnyI+AqH/u2IWUtFddRACSxxNF+jSPiKEYL8lf8FHeaUOnjiscAu2JCG6dwpkvrWgtfabNzRleLiGHGNPS1bTzPKnP7UelTI6pD+,iv:CObMMSj+6toJ0jkqIOTbxVtRdvqCJ4jLRKZ+/ZlgnCo=,tag:XDliv2jPGA8EftCIyPw62A==,type:str]
    identity.pub: ENC[AES256_GCM,data:QIV/bJn2AeEBufKCEiAjwkSO5y+rbhLkikfzSfe6fgbnzOQzZzf/BDnUVKom5v68ZKTmw/Gev858OnkOsI8NnP74o2Szt37I6vcAg9ZEzKhalIL45vwllplqQkmh9JWOhivrKd3FrR2tTBauFyz0qCqXkSkpaWGcx/V6Ntx9M9rynextQccbUGi5U3xQHGwfhQhjf7XSvl9Rpl4ZZevjBvvwW1/dupNRCYo9iK873c1mRE4JfKJt8qfVtNKYHD/0TT0zK4d2cbwfwHscCw==,iv:a57wQps+1yP1dUhdKcxlCPjmgwXwNtlb6V6EDdk6ROs=,tag:qArkV5AauMQi6kKvqvV2TQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:PK9oNAD5isZPLH76AYuvkZQy9OrJ9syeYUXrKOaKw3Z+Nvzm3gmM6Z6g1QSGv3LTXuVDxKPjC9/76+SJ6uDOgSG16s3YWbROtm5FYxgt4cMluxhNyFBORAmX8XJfbaJp0Y/CyZgdOHqImpEodlbAWvNdbuL6rrSpP7QyOv9qntRGnU6O9SIzjnzX7H0DKSQLqQ0vYVx/gGgkA1myJeC7At4jcvV+vUVZyySV,iv:zKzGCW17WfDiJ7EQ9WcoUiTdBktFpZtRgY3lZvJ3kbs=,tag:n3aIXaFywhK7y4PeD6ivOQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVTBibm94Uzl6ZUhxMm5W
            bHdZMjhUNjBJdnRVek5IRlBMTW13RzQ1bGw4ClB0Y1kxZnI3QlNoYnExckVTbzBz
            RGJQbVE5RTkwQmpRSVFYNm1QRm55a3MKLS0tIHNUS3QwTlFXTTlUdFZmUUEycVFS
            MkprZ2p6bTE4cHpDRUF0c2lYbzMwTjgKa5VAVbQRS0i9acnL0BTKpxf5e2Yhx6ux
            KzZo7Skxald7p95WOiDXjnmgjiiBHmU8xvvqQQUktjCOiBfCET4xjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-08T06:32:49Z"
    mac: ENC[AES256_GCM,data:9LlXoFBY3ztYM1dYoN/olrtUjqUBHbuYCR3bUjzLlWHWmL9vIkLsqBsJYFTqi9bHW36uK5vlx2+x8BO91mnh/C6+Fbcq3BaHFgks5Q4aweeDXsS3muogCkeSUwT42AA033feSgMwr/a/irtgqSY34+vd/4qPK4i3TW9y4f9btkc=,iv:IHqwC68TRdMnxFjJLlDjpV+wELrzDgII4cOcC6RYUxU=,tag:aF7Tqmqvf/YyyIeyDP68Eg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
