apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jJo03TKf9JwwtR6ti+EUrpsRJTwy9pc714DXFBvPDeAzxUdarjb/w3dUi38oRyL3+hhafHVW/L/D3HBnjKVEaIiWVwv69lV+Ukh0W1y/Pl7xUCpi7ZrDocnhzV5l+V9OAmFAfFLdr9i/wgWo/UA0TU39Xtz3g6A5je+9J+tRZzePBwCmZMmjmSWk4Esbt9qpV6tCejnx8arIyQxY8beWrk5ael7MbNhVYXFHQhjPwR1buS5jBkIRW4U9ERq+tE1crrtVHqEgFiF9W4qdD7S2w0GbKHAi3PTJU0Mn+CaF7Iig80TWZiIJRvyMUxF/1JF3w2wIE7TH1P/KOoCvJQ2RsEVXpiTQLl7IQzylRDe664VV1xL/7yyQ12e55L+ksujA,iv:KG4h2EsNGNGtB4cH4HOrETnpTMDSzydJDLuvCCiyw6E=,tag:i3y/oCkNc8qfp+6mpW747Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:UL8SQvRECcpeL/9wqXwZsCoZ9AoxFrQVKGu0KpkMwNEly3MoBGystq8VWV/6dzJk6Z+IKEisshAJ5M97SXgUp+rS8AFAG4vj9l4DujrpNkyk/6cY7yvvxGx44Ia88c3720ijaC7UMEEFVrd3cD4OYDT07G3N9qM/M7q3s9kXzRatgwWZSBuwcl/EMTDYgdxtX9FN3CphiinH9kCGcOcmmXOF3Jzto9+seA0saqENogAQJ31TFUNlPVBi3Wb+O3ik3LGIm45HgSE25QjqlA==,iv:904fJSZ4IVuETX2Na1lzKewMCQQE9VP+Vibd5f/fP5o=,tag:5XwWK2zpHhoKlBlq6CQnVw==,type:str]
    known_hosts: ENC[AES256_GCM,data:32P1REx8xziT2Zf+1vj4gIyCAVQoxOIAngLSbwJ0iGLcmcAFetTbcl7s07N9RHsLXDzcQVIteQYB+w0dPc63QSSAt89u5RufZHnhBtNOYlY+u+0WZVf3A1moJe4BobmwmkugTbS+MfEuufHQQoQOgT0KnMr8lLl6y28SkyNG63TWg/acyWE2rWx1H1C0QdR7NX3nsKoYkBoAyrVKYnPe0U7J55wH8BQPV724,iv:VKTtx344y+kJxdWG+4yimnPQHZNxVeV2YK8Ivtm6EcI=,tag:v/l/Ue267SpX9eUESwNxGw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUmwzUnFmL1h4OXh4ZDFT
            cE1ubGNnRzY3dEc3Y25wMTV3OFFtRkVhcDFnCnVCQUVqM1kzYm94Q2pNT2tjSllP
            QWs5WTR4cG9pdU9rUHFvNDBqckw4M0EKLS0tIHZUNHlTeUcvSnU4K1FHb2Q2Tm9u
            WjR5VS9zOTlNZE1sNy9IL2lWelhjY0EKM3GWXmV/oWvGoMsBmn2lJXVo8NOXYw54
            quPqlQFYc6Lf7E9gVMmPXmUJ0z/sxSuK66S9dYomIHypRE3ycced6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T10:29:28Z"
    mac: ENC[AES256_GCM,data:52FIeu2C8bni0pCGVQJ0Z5rEGXFFO+p4gGlxTutvAC2lhmK5CvTCpx81xyw0h4cz+Dbf8w1PN+gyV+GrS4d3pXlec2tdpAXKgy/in99vrI/yq64WiO2VkSUUdZgblzm1M1MJUBQIC36cPHgbNKmvQFU/1UewH5Sj+zWY8VQ2KIY=,iv:6CfCeJTSUaATIXLrQu+vk6Upm3rG61quyhvA0Kig/mM=,tag:u/J8zW8K0Ps8QsfTpn4xWw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
