apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:I9MIyvqu8PYj6qlksZ0epmQ1ym78TpskNRuaFO2pYtdzvWpkDQpGhml/2QnU+OgOpXdbPIj3973OSSn0J8vMyebsuvDkTF8bziKb2q09mwDDJnf64VvqoaMO0+cNec6OHdOYnKKNuk+WI2u/4E9JAbbc+WuDKNyc7veKJla0rPNxwTrYyBvVYHNmUe9i8XIOMo33nNNgaxrbMvXxIijGjME31VGDyetiCxll3XRJaIbr+kCGy5P1p5SordpgHP+4VyViSQjA+DYwAbzOL7tN2a6PrOMCQp+lPh9JRyk2U2MlnX+YWGQ62zvm9tGCgbVtSnKwKxPM8LGUlv3OfDI6t3hbXg6Ny52PXzaQKStLhq8PdtDs7hUs4G1oH+H65YyP,iv:nHzDo0r9dw2QI+Sck8OgwLOopznJF7hqKNtRAUIcQhM=,tag:Nby5MYQKLAQB5iv68aerIQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:BMcySQ7uCAetn2f7CCmm0EgRtwJurMcApRcbUITcHCsmyog8HmC74i185scy8T/Wyq/U6AkCbNlqGc4eNFYX4dLw2DcJkzSesd3dDVvuHlO/OgwhJRcc82X6HfRemvZ4BavVn9efrJlcNNYcf1TlkEHu529X3Aur2Uy0lQnDPZvpjglSRdBbPngunB9wFEFNi+nV8tFS9akXJM+9jBuTcnaI7+F8uRKip/SoHiflI60rx97kJo48iJmtFA9UOV3tdRq602DFAQtI/TT21A==,iv:LjK1t2JNokKylHXtsHPtL+V7dcaq9KxuVufrzHwD+B8=,tag:hs0v3/B21POuj1/uu/I71g==,type:str]
    known_hosts: ENC[AES256_GCM,data:4MyV1r3sw6cBrmJrvzhQlgUXUIgXVWOruCrDbXD0cgUR7IvDcfKA+9w12ph3KNWj4eMCb9jJcestUoYJjqFr/JzZ/k3dPauyTyk4IeVrtp7yqzFygUs6+ymAdRSY04CEDxQ2+cCdvtYwRPxECZ/uIOk/JJIJ/KaZ/ncHbbB9BznCj4+l4KRF9oBgyj8MWOLT4CWlJF5OAMsCL5ddd8zDL4lYJKRpxb6rKGzN,iv:Q6QNx4QSacw7vsGXvLCfQeuCLnDnbAtA8WZ/EW+dFDU=,tag:9eQMZhgKDXX/j4u426HW4A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSm8xV1QzOFAzRHg2UjIz
            MmNlMXp1Y0NETUVEbUNtc0hJN1Y1UE5VbkRJCmtBZEhQU0J0M01PcnZENHFCMW5a
            bU1ZYXlnYVlXUXVEN28yTHBRZDJtK1EKLS0tIHFSWFphZ2N0VWRqQWZ6VGVqcjFl
            aUtNbmJ2SkVodzA0QjNLLytLdjNLYlUKQOnbLOpOcjul8CJ24MgV6arBvDx02t9V
            ghxUhqvpyWh+k9XSY00jinHUz9aOYN4jhNp5/TNwPbZRCeWes5pG6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T14:58:04Z"
    mac: ENC[AES256_GCM,data:j3RnpKgnpcpZuYmGpyyq1aCr0lGNXCNE2p34N3m3PVRfVaIgWtplxrFLZm+p1t+0hDjgAJE63nW57+MxtoJtSyH9H/3bjUewdGYExOrMVTByVwgV8q6OJ18xeGSBak3FxT1iAhFCWhTiHnbdlL6x5gR4+/j5BpkPP8W3dDI68vQ=,iv:naQEbCZyFT9snV/Y7sSUtstYELdgW4KgnJUKB3WA4z8=,tag:1JIFUh7ISSpVaj6sVjQR4Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
