apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Zj1Pyw2i+E3aYdeOVdxgDlG8w4YjprChXFfiS42OTNtAG2yaGOLAe9cYl2ZeNrpDieZ6urboqnw3E5p3ED8UwylPbiujzYNVroG2OeAg9beuDSUUfav3APQ6+9k/TH88yoCOzNpn5mClZn+lnr48CMiUYm3pAeQSK0YK42Ks0vjdex2CRdD0RQaW5zMxfu++wHDuGMTSC0p8r3Zu5ku8jGdA19h3lVHmjXGvv5Ltk7W+rdXWxFIjpL1MP4wcDiXCs11Cn4KuEBDL4bEe/pj6w7qCMd3s83OskVOn0OkfFo+hy55Vei19TIW3lYsI1tmIxQXNKfLcR5XM3M7XYJA3ZYehk9SNY5MCXejXrnvxyZjXqIyqW+/u/banrL6J3f8O,iv:J571218Q4NR9W2aBLXSHVp0q1bUgrvjTvyt0MdQpegw=,tag:QNXcU5MlsJRaUlihK5W2Xw==,type:str]
    identity.pub: ENC[AES256_GCM,data:S+q32t/bZ5DjDCuvqeJR73DoccaYosx/XPuiEjylwPUlV/Eu5Npp/Zj3b04Sbtw0amXvl4OY2XyXFwVlrHZLRp5g56UNMgmaXw37IfxATcu55RH8F3sWIaKHXl/YXiJAn1i0KowMlQwJU3FYMP/MWgwdugL8Ags+amUaTVAKeAT3IPu4VJrTF59m5nkBjY56fieCsF0Sq9dKVlZhtxO+oDJu+mNVDsSGQAoAOaRX+psLhyeKxAmxioWIFCRF+63gBMBvdcBaq6E9xsk3Xg==,iv:yQ5ymGN1yjQqckO4aUFs7CwPZSqz9AG3RV36rUY2s/g=,tag:Yzb2s7r3Ul3U89aNTP2x3w==,type:str]
    known_hosts: ENC[AES256_GCM,data:61H//t/tJA91ubqDilFm6GQMOJZJ6EupM7MBVIWGczWyk47VXJUdVv2xDx8Cj1iPP8+H+uq6P2b8A2hIGCSB+gXeNCCbZzWDA42cQeGAeqZuUdIpaZ5zRcDGWBsGDtKekDMxZpb5wmLUe23aAkhEJrfZ9QdGZLVhHr5DlPh3wEueT7thc5YOaRyXDBTUWYlmTVk6iXYJd7YzQGWpO0DfycRcNLDKsC39x5OK,iv:p0LchOELDyLBOgFAkRP71xRFkEjBrUT2Bw/vA6yfUX0=,tag:hWyLZHDY9VB3t6QTWwtnmA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1p2xm8zt9mkg0edhydpsen5vkkmqjuucgexzcvztvf0mhq3hepfrqw37ttw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBT3hlamJNTURVa3JRamFt
            M0NOYytNZGl6Ni93TVA3RXVNSTQ2YjlKZG5FCk15NGlmS3NPdHU3ZlV5RXdRdGdn
            TW9WeVhzOERrTjg0eWhKejVHaXdUSW8KLS0tIDVNeCtUNHBLVHpXOGY4Vk1wR1hn
            Q0dxWXo4MHpzSWw4WHQ4YXZ6bzhKNDgKBpoNGm+fv8NqjtpfXtHvfyBUpl2RzpJe
            phDJTP9cFan8fkG8v/NNBknCDQ38CIEI/J/0bVoqnOvglR6rAXXcbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T14:56:32Z"
    mac: ENC[AES256_GCM,data:pVBX60W0ocbyC4m0Yj+UfMYz0OkOpVDkmfG4LUTjcOHSfTTwPA1BchGyn0apPnKOou8GQ7XpWCToSpu6az5yF3Rg/CJYbdv6a8ALPvzvPH2kxkMxCmm9Mcu0WTEp5aXuR5bdPthzfB3NQMMF14XnUpqeNTwfR4iV4rVzu0/TXSs=,iv:9rirst56nm09fwFxh+fYWq2rzo1F8g0iTwZlnZyVnCw=,tag:o014a6M2i0Ad/0qRucOT2w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
