apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cert-manager-webhook-hetzner
    namespace: cert-manager
spec:
    interval: 5m
    chart:
        spec:
            chart: cert-manager-webhook-hetzner
            version: 0.6.2
            sourceRef:
                kind: HelmRepository
                name: hcloud
                namespace: flux-system
            interval: 2h
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
      groupName: "base.noitl.space"
      certManager:
        serviceAccountName: cert-manager
