apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 15m
  chart:
    spec:
      chart: immich
      version: 25.18.22
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: immich
  values:
    TZ: Europe/Berlin
    immich:
      log_level: debug
    credentials:
      storj:
        type: s3
        name: storj
        url: https://gateway.storjshare.io
        accessKey: ${STORJ_ACCESS_KEY}
        secretKey: ${STORJ_SECRET_KEY}
        bucket: ${STORJ_BUCKET}
        encrKey: ${STORJ_VOLSYNC_ENCRYPTION_KEY}
        path: ""
      aws:
        type: s3
        name: aws
        url: "https://s3.eu-central-1.amazonaws.com"
        accessKey: ${AWS_ACCESS_KEY}
        secretKey: ${AWS_SECRET_KEY}
        bucket: "talos-cnpg-backups"
        encrKey: ${AWS_ENCRYPTION_KEY}
        path: ""
    cnpg:
      main:
        cluster:
          instances: 1
          singleNode: true
        mode: recovery
        backups:
          enabled: true
          credentials: aws
          revision: "1"
        recovery:
          method: object_store
          credentials: aws
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: pics.${BASE_DOMAIN}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: ${CERTMANAGER_ISSUER}
          homepage:
            enabled: true
            group: Medien
            widget:
              custom:
                key: ${IMMICH_HOMEPAGE_API_KEY}
    persistence:
      mlconfig:
        enabled: true
        type: emptyDir
        targetSelector:
          machinelearning:
            machinelearning:
              mountPath: /.config
      mlothercache:
        enabled: true
        type: emptyDir
        targetSelector:
          machinelearning:
            machinelearning:
              mountPath: /.cache
      library:
        type: nfs
        server: ${NFS_HOST}
        path: /mnt/pool1/immich/library
        readOnly: false
        autoPermissions:
          enabled: false
      uploads:
        type: nfs
        server: ${NFS_HOST}
        path: /mnt/pool1/immich/uploads
        readOnly: false
        autoPermissions:
          enabled: false
      backups:
        type: nfs
        server: ${NFS_HOST}
        path: /mnt/pool1/immich/backups
        readOnly: false
        autoPermissions:
          enabled: false
      thumbs:
        type: nfs
        server: ${NFS_HOST}
        path: /mnt/pool1/immich/thumbs
        readOnly: false
        autoPermissions:
          enabled: false
      profile:
        type: nfs
        server: ${NFS_HOST}
        path: /mnt/pool1/immich/profile
        readOnly: false
        autoPermissions:
          enabled: false
      video:
        type: nfs
        server: ${NFS_HOST}
        path: /mnt/pool1/immich/video
        readOnly: false
        autoPermissions:
          enabled: false
    securityContext:
      container:
        UMASK: "0022"
        runAsGroup: 568
        runAsUser: 568
      pod:
        fsGroupChangePolicy: OnRootMismatch