apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: helm-repos
  namespace: flux-system
resources:
  - cert-manager-webhook-hetzner.yaml
  - bjw-s.yaml
  - cilium.yaml
  - cloudnative-pg.yaml
  - hcloud.yaml
  - home-ops-mirror.yaml
  - jetstack.yaml
  - kustomization.yaml
  - metallb.yaml
  - node-feature-discovery.yaml
  - openebs.yaml
  - prometheus-community.yaml
  - spegel.yaml
  - truecharts.yaml
# more goes here!
